# Generated by Django 3.0.5 on 2020-05-20 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254, unique=True)),
                ('user_id', models.IntegerField(default='', max_length=254)),
                ('role', models.CharField(default='', max_length=254)),
                ('race', models.CharField(default='', max_length=254)),
                ('appearance', models.CharField(default='', max_length=254)),
                ('gender', models.CharField(default='', max_length=254)),
                ('gold', models.CharField(default='', max_length=254)),
                ('xp', models.CharField(default='', max_length=254)),
                ('level', models.CharField(default='', max_length=254)),
                ('strength', models.CharField(default='', max_length=254)),
                ('dexterity', models.CharField(default='', max_length=254)),
                ('constitution', models.CharField(default='', max_length=254)),
                ('wisdom', models.CharField(default='', max_length=254)),
                ('charisma', models.CharField(default='', max_length=254)),
                ('created_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
