# Generated by Django 3.0.5 on 2020-05-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('characters', '0001_initial'), ('characters', '0002_auto_20200520_1115'), ('characters', '0003_character_main_character'), ('characters', '0004_character_banned'), ('characters', '0005_auto_20200520_2117'), ('characters', '0006_auto_20200521_1012'), ('characters', '0007_auto_20200521_1555'), ('characters', '0008_auto_20200522_1051'), ('characters', '0009_auto_20200522_1705'), ('characters', '0010_auto_20200522_1706'), ('characters', '0011_auto_20200522_1741'), ('characters', '0012_character_intelligence'), ('characters', '0013_auto_20200525_1243'), ('characters', '0014_auto_20200525_1318'), ('characters', '0015_auto_20200525_1646'), ('characters', '0016_auto_20200525_1651'), ('characters', '0017_auto_20200525_1652'), ('characters', '0018_auto_20200525_1656')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254, unique=True)),
                ('user_id', models.IntegerField(default='')),
                ('role', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='', max_length=254)),
                ('race', models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half Elf', 'Half Elf'), ('Halfling', 'Halfling'), ('Half Orc', 'Half Orc'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], default='', max_length=254)),
                ('appearance', models.CharField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=254)),
                ('gold', models.CharField(default='0', max_length=254)),
                ('xp', models.CharField(default='0', max_length=254)),
                ('level', models.CharField(default='1', max_length=254)),
                ('strength', models.CharField(default='0', max_length=254)),
                ('dexterity', models.CharField(default='0', max_length=254)),
                ('constitution', models.CharField(default='0', max_length=254)),
                ('wisdom', models.CharField(default='0', max_length=254)),
                ('charisma', models.CharField(default='0', max_length=254)),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('main_character', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=254)),
                ('banned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=254)),
                ('intelligence', models.CharField(default='0', max_length=254)),
            ],
        ),
    ]
