# Generated by Django 3.0.5 on 2020-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='user_id',
            field=models.IntegerField(default=''),
        ),
    ]
