# Generated by Django 3.0.5 on 2020-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200520_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_character',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=254),
        ),
    ]
