# Generated by Django 3.0.5 on 2020-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_main_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='banned',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=254),
        ),
    ]
