# Generated by Django 3.0.5 on 2020-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200520_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
