# Generated by Django 3.0.5 on 2020-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200521_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Gnome', 'Gnome'), ('Half Orc', 'Half Orc')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('Warrior', 'Warrior'), ('Bard', 'Bard'), ('Priest', 'Priest'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Rogue', 'Rogue'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.CharField(default='1', max_length=254),
        ),
    ]
