# Generated by Django 3.0.5 on 2020-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200522_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
