# Generated by Django 3.0.5 on 2020-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20200522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
