# Generated by Django 3.0.5 on 2020-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20200525_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half Elf', 'Half Elf'), ('Halfling', 'Halfling'), ('Half Orc', 'Half Orc'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], default='', max_length=254),
        ),
    ]
